
// taken from: https://firebase.google.com/docs/reference/js/firebase.auth.Auth
const ERROR_CODE = {
        ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL: 'auth/account-exists-with-different-credential',
        ARGUMENT_ERROR: 'auth/argument-error',
        AUTH_DOMAIN_CONFIG_REQUIRED: 'auth/auth-domain-config-required',
        CANCELLED_POPUP_REQUEST: 'auth/cancelled-popup-request',
        CAPTCHA_CHECK_FAILED: 'auth/captcha-check-failed',
        CREDENTIAL_ALREADY_IN_USE: 'auth/credential-already-in-use',
        CUSTOM_TOKEN_MISMATCH: 'auth/custom-token-mismatch',
        EMAIL_ALREADY_IN_USE: 'auth/email-already-in-use',
        EXPIRED_ACTION_CODE: 'auth/expired-action-code',
        INVALID_ACTION_CODE: 'auth/invalid-action-code',
        INVALID_CONTINUE_URI: 'auth/invalid-continue-uri',
        INVALID_CREDENTIAL: 'auth/invalid-credential',
        INVALID_CUSTOM_TOKEN: 'auth/invalid-custom-token',
        INVALID_EMAIL: 'auth/invalid-email',
        INVALID_PERSISTENCE_TYPE: 'auth/invalid-persistence-type',
        INVALID_PHONE_NUMBER: 'auth/invalid-phone-number',
        INVALID_USER_TOKEN: 'auth/invalid-user-token',
        INVALID_VERIFICATION_CODE: 'auth/invalid-verification-code',
        INVALID_VERIFICATION_ID: 'auth/invalid-verification-id',
        MISSING_ANDROID_PKG_NAME: 'auth/missing-android-pkg-name',
        MISSING_CONTINUE_URI: 'auth/missing-continue-uri',
        MISSING_IOS_BUNDLE_ID: 'auth/missing-ios-bundle-id',
        MISSING_PHONE_NUMBER: 'auth/missing-phone-number',
        NULL_USER: 'auth/null-user',
        OPERATION_NOT_ALLOWED: 'auth/operation-not-allowed',
        OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT: 'auth/operation-not-supported-in-this-environment',
        POPUP_BLOCKED: 'auth/popup-blocked',
        POPUP_CLOSED_BY_USER: 'auth/popup-closed-by-user',
        QUOTA_EXCEEDED: 'auth/quota-exceeded',
        TENANT_ID_MISMATCH: 'auth/tenant-id-mismatch',
        TIMEOUT: 'auth/timeout',
        UNAUTHORIZED_CONTINUE_URI: 'auth/unauthorized-continue-uri',
        UNAUTHORIZED_DOMAIN: 'auth/unauthorized-domain',
        UNSUPPORTED_PERSISTENCE_TYPE: 'auth/unsupported-persistence-type',
        USER_DISABLED: 'auth/user-disabled',
        USER_NOT_FOUND: 'auth/user-not-found',
        USER_TOKEN_EXPIRED: 'auth/user-token-expired',
        WEAK_PASSWORD: 'auth/weak-password',
        WRONG_PASSWORD: 'auth/wrong-password'

}

export default FIREBASE_AUTH_ERRORCODE = {
    APPLY_ACTION_CODE: {
        EXPIRED_ACTION_CODE: ERROR_CODE.EXPIRED_ACTION_CODE,
        INVALID_ACTION_CODE: ERROR_CODE.INVALID_ACTION_CODE,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND
    },
    CHECK_ACTION_CODE: {
        EXPIRED_ACTION_CODE: ERROR_CODE.EXPIRED_ACTION_CODE,
        INVALID_ACTION_CODE: ERROR_CODE.INVALID_ACTION_CODE,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND
    },
    CONFIRM_PASSWORD_RESET: {
        EXPIRED_ACTION_CODE: ERROR_CODE.EXPIRED_ACTION_CODE,
        INVALID_ACTION_CODE: ERROR_CODE.INVALID_ACTION_CODE,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND,
        WEAK_PASSWORD: ERROR_CODE.WEAK_PASSWORD
    },
    CREATE_USER_WITH_EMAILPASSWORD: {
        EMAIL_ALREADY_IN_USE: ERROR_CODE.EMAIL_ALREADY_IN_USE,
        INVALID_EMAIL: ERROR_CODE.INVALID_EMAIL,
        OPERATION_NOT_ALLOWED: ERROR_CODE.OPERATION_NOT_ALLOWED,
        WEAK_PASSWORD: ERROR_CODE.WEAK_PASSWORD
    },
    FETCH_SIGNIN_METHODS_FOR_EMAIL: {
        INVALID_EMAIL: ERROR_CODE.INVALID_EMAIL,
    },
    GET_REDIRECT_RESULT: {
        ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL: ERROR_CODE.ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL,
        AUTH_DOMAIN_CONFIG_REQUIRED: ERROR_CODE.AUTH_DOMAIN_CONFIG_REQUIRED,
        CREDENTIAL_ALREADY_IN_USE: ERROR_CODE.CREDENTIAL_ALREADY_IN_USE,
        EMAIL_ALREADY_IN_USE: ERROR_CODE.EMAIL_ALREADY_IN_USE,
        OPERATION_NOT_ALLOWED: ERROR_CODE.OPERATION_NOT_ALLOWED,
        OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT: ERROR_CODE.OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT,
        TIMEOUT: ERROR_CODE.TIMEOUT
    },
    SEND_PASSWORD_RESET_EMAIL: {
        INVALID_CONTINUE_URI: ERROR_CODE.INVALID_CONTINUE_URI,
        INVALID_EMAIL: ERROR_CODE.INVALID_EMAIL,
        MISSING_ANDROID_PKG_NAME: ERROR_CODE.MISSING_ANDROID_PKG_NAME,
        MISSING_CONTINUE_URI: ERROR_CODE.MISSING_CONTINUE_URI,
        MISSING_IOS_BUNDLE_ID: ERROR_CODE.MISSING_IOS_BUNDLE_ID,
        UNAUTHORIZED_CONTINUE_URI: ERROR_CODE.UNAUTHORIZED_CONTINUE_URI,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND
    },
    SEND_SIGNIN_LINK_TO_EMAIL:  {
        ARGUMENT_ERROR: ERROR_CODE.ARGUMENT_ERROR,
        INVALID_EMAIL: ERROR_CODE.INVALID_EMAIL,
        MISSING_ANDROID_PKG_NAME: ERROR_CODE.MISSING_ANDROID_PKG_NAME,
        MISSING_CONTINUE_URI: ERROR_CODE.MISSING_CONTINUE_URI,
        MISSING_IOS_BUNDLE_ID: ERROR_CODE.MISSING_IOS_BUNDLE_ID,
        INVALID_CONTINUE_URI: ERROR_CODE.INVALID_CONTINUE_URI,
        UNAUTHORIZED_CONTINUE_URI: ERROR_CODE.UNAUTHORIZED_CONTINUE_URI
    },
    SET_PERSISTENCE: {
        INVALID_PERSISTENCE_TYPE: ERROR_CODE.INVALID_PERSISTENCE_TYPE,
        UNSUPPORTED_PERSISTENCE_TYPE: ERROR_CODE.UNSUPPORTED_PERSISTENCE_TYPE
    },
    SIGNIN_ANONYMOUSLY: {
        OPERATION_NOT_ALLOWED: ERROR_CODE.OPERATION_NOT_ALLOWED
    },
    SIGNIN_WITH_CREDENTIAL: {
        ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL: ERROR_CODE.ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL,
        INVALID_CREDENTIAL: ERROR_CODE.INVALID_CREDENTIAL,
        OPERATION_NOT_ALLOWED: ERROR_CODE.OPERATION_NOT_ALLOWED,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND,
        WRONG_PASSWORD: ERROR_CODE.WRONG_PASSWORD,
        INVALID_VERIFICATION_CODE: ERROR_CODE.INVALID_VERIFICATION_CODE,
        INVALID_VERIFICATION_ID: ERROR_CODE.INVALID_VERIFICATION_ID
    },
    SIGNIN_WITH_CUSTOM_TOKEN: {
        CUSTOM_TOKEN_MISMATCH: ERROR_CODE.CUSTOM_TOKEN_MISMATCH,
        INVALID_CUSTOM_TOKEN: ERROR_CODE.INVALID_CUSTOM_TOKEN
    },
    SIGNIN_WITH_EMAILPASSWORD: {
        INVALID_EMAIL: ERROR_CODE.INVALID_EMAIL,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND,
        WRONG_PASSWORD: ERROR_CODE.WRONG_PASSWORD,
    },
    SIGNIN_WITH_EMAILLINK: {
        EXPIRED_ACTION_CODE: ERROR_CODE.EXPIRED_ACTION_CODE,
        INVALID_EMAIL: ERROR_CODE.INVALID_EMAIL,
        USER_DISABLED: ERROR_CODE.USER_DISABLED
    },
    SIGNIN_WITH_PHONENUMBER: {
        CAPTCHA_CHECK_FAILED: ERROR_CODE.CAPTCHA_CHECK_FAILED,
        INVALID_PHONE_NUMBER: ERROR_CODE.INVALID_PHONE_NUMBER,
        MISSING_PHONE_NUMBER: ERROR_CODE.MISSING_PHONE_NUMBER,
        QUOTA_EXCEEDED: ERROR_CODE.QUOTA_EXCEEDED,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        OPERATION_NOT_ALLOWED: ERROR_CODE.OPERATION_NOT_ALLOWED
    },
    SIGNIN_WITH_POPUP: {
        ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL: ERROR_CODE.ACCOUNT_EXITS_WITH_DIFFERENT_CREDENTIAL,
        AUTH_DOMAIN_CONFIG_REQUIRED: ERROR_CODE.AUTH_DOMAIN_CONFIG_REQUIRED,
        CANCELLED_POPUP_REQUEST: ERROR_CODE.CANCELLED_POPUP_REQUEST,
        OPERATION_NOT_ALLOWED: ERROR_CODE.OPERATION_NOT_ALLOWED,
        OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT: ERROR_CODE.OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT,
        POPUP_BLOCKED: ERROR_CODE.POPUP_BLOCKED,
        POPUP_CLOSED_BY_USER: ERROR_CODE.POPUP_CLOSED_BY_USER,
        UNAUTHORIZED_DOMAIN: ERROR_CODE.UNAUTHORIZED_DOMAIN
    },
    SIGNIN_WITH_REDIRECT: {
        AUTH_DOMAIN_CONFIG_REQUIRED: ERROR_CODE.AUTH_DOMAIN_CONFIG_REQUIRED,
        OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT: ERROR_CODE.OPERATION_NOT_SUPPORTED_IN_THIS_ENVIRONMENT,
        UNAUTHORIZED_DOMAIN: ERROR_CODE.UNAUTHORIZED_DOMAIN
    },
    UPDATE_CURRENT_USER: {
        INVALID_USER_TOKEN: ERROR_CODE.INVALID_USER_TOKEN,
        USER_TOKEN_EXPIRED: ERROR_CODE.USER_TOKEN_EXPIRED,
        NULL_USER: ERROR_CODE.NULL_USER,
        TENANT_ID_MISMATCH: ERROR_CODE.TENANT_ID_MISMATCH
    },
    VERIFY_PASSWORD_RESET_CODE: {
        EXPIRED_ACTION_CODE: ERROR_CODE.EXPIRED_ACTION_CODE,
        INVALID_ACTION_CODE: ERROR_CODE.INVALID_ACTION_CODE,
        USER_DISABLED: ERROR_CODE.USER_DISABLED,
        USER_NOT_FOUND: ERROR_CODE.USER_NOT_FOUND
    }
} 

